# Generated by Django 3.0.5 on 2020-08-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0002_fun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answertaskone',
            name='student_key',
        ),
        migrations.RemoveField(
            model_name='answertasktwo',
            name='student_key',
        ),
        migrations.RemoveField(
            model_name='coachingclass',
            name='user_key',
        ),
        migrations.DeleteModel(
            name='CommonTaskOne',
        ),
        migrations.DeleteModel(
            name='CommonTaskTwo',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='coaching_class_key',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='user_key',
        ),
        migrations.DeleteModel(
            name='Fun',
        ),
        migrations.RemoveField(
            model_name='student',
            name='faculty_key',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_key',
        ),
        migrations.DeleteModel(
            name='AnswerTaskOne',
        ),
        migrations.DeleteModel(
            name='AnswerTaskTwo',
        ),
        migrations.DeleteModel(
            name='CoachingClass',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
