# Generated by Django 3.0.5 on 2020-08-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0004_answertaskone_answertasktwo_coachingclass_commontaskone_commontasktwo_faculty_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='answertaskone',
            name='answer',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answertasktwo',
            name='answer',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
    ]
