# Generated by Django 3.0.5 on 2020-08-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0005_auto_20200811_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='answertaskone',
            name='word_count',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answertasktwo',
            name='word_count',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
