# Generated by Django 3.0.5 on 2020-08-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0007_auto_20200811_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='answertasktwo',
            name='coherence_and_cohension',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answertasktwo',
            name='coherence_and_cohension_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answertasktwo',
            name='grammer_range_accuracy',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answertasktwo',
            name='grammer_range_accuracy_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answertasktwo',
            name='lexical_resource',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answertasktwo',
            name='lexical_resource_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answertasktwo',
            name='task_achievement',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answertasktwo',
            name='task_achievement_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
