# Generated by Django 3.0.5 on 2020-08-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0008_auto_20200812_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='answertasktwo',
            name='overall_band',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
