# Generated by Django 3.0.5 on 2020-08-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0009_answertasktwo_overall_band'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertasktwo',
            name='coherence_and_cohension',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='answertasktwo',
            name='grammer_range_accuracy',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='answertasktwo',
            name='lexical_resource',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='answertasktwo',
            name='overall_band',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='answertasktwo',
            name='task_achievement',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
