# Generated by Django 3.0.5 on 2020-08-13 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0010_auto_20200812_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerTaskOneAcademic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('word_count', models.PositiveSmallIntegerField()),
                ('photo', models.ImageField(null=True, upload_to='ielts/answer/academic/')),
                ('is_checked', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('checked_time', models.DateTimeField(null=True)),
                ('task_achievement', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('task_achievement_remark', models.TextField(blank=True, null=True)),
                ('coherence_and_cohension', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('coherence_and_cohension_remark', models.TextField(blank=True, null=True)),
                ('lexical_resource', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('lexical_resource_remark', models.TextField(blank=True, null=True)),
                ('grammer_range_accuracy', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('grammer_range_accuracy_remark', models.TextField(blank=True, null=True)),
                ('overall_band', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('student_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ielts.Student')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerTaskOneGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('word_count', models.PositiveSmallIntegerField()),
                ('is_checked', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('checked_time', models.DateTimeField(null=True)),
                ('task_achievement', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('task_achievement_remark', models.TextField(blank=True, null=True)),
                ('coherence_and_cohension', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('coherence_and_cohension_remark', models.TextField(blank=True, null=True)),
                ('lexical_resource', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('lexical_resource_remark', models.TextField(blank=True, null=True)),
                ('grammer_range_accuracy', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('grammer_range_accuracy_remark', models.TextField(blank=True, null=True)),
                ('overall_band', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('student_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ielts.Student')),
            ],
        ),
        migrations.CreateModel(
            name='CommonTaskOneAcademic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('photo', models.ImageField(null=True, upload_to='ielts/question/academic/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommonTaskTwoGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='answertaskone',
            name='student_key',
        ),
        migrations.DeleteModel(
            name='CommonTaskOne',
        ),
        migrations.DeleteModel(
            name='AnswerTaskOne',
        ),
    ]
