# Generated by Django 3.0.5 on 2020-08-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0011_auto_20200814_0216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommonTaskTwoGeneral',
            new_name='CommonTaskOneGeneral',
        ),
    ]
