# Generated by Django 3.0.5 on 2020-08-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0012_auto_20200815_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='faculty_id',
            field=models.IntegerField(default=46),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='mobile_number',
            field=models.BigIntegerField(default=9898989898),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='mobile_number',
            field=models.BigIntegerField(default=9898989898),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(default=69),
            preserve_default=False,
        ),
    ]
