# Generated by Django 3.0.5 on 2020-08-22 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0013_auto_20200822_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='faculty_id',
            new_name='faculty_uid',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='student_uid',
        ),
    ]
