# Generated by Django 3.0.5 on 2020-08-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0014_auto_20200822_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='commontaskoneacademic',
            name='uid',
            field=models.IntegerField(null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commontaskonegeneral',
            name='uid',
            field=models.IntegerField(null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commontasktwo',
            name='uid',
            field=models.IntegerField(null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commontaskoneacademic',
            name='question',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='commontaskonegeneral',
            name='question',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='commontasktwo',
            name='question',
            field=models.TextField(unique=True),
        ),
    ]
